extends: airbnb/base
plugins:
  - import
globals:
  window: true
  document: true
  navigator: true
  requestAnimationFrame: true
rules:
  key-spacing:
    - 1
    - align: colon
  no-multi-spaces:
    - 1
    - exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true
        AssignmentExpression: true
  no-multiple-empty-lines:
    - 1
    - max: 1
  strict:
    - 0
  no-underscore-dangle:
    - 0
  class-methods-use-this:
    - 1
  max-len:
    - 1
  linebreak-style:
    - 0
